group 'com.jiguang.jpush'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.jiguang.jpush"
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 19
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'cn.jiguang.sdk:jpush-google:5.6.0'
}